### ISSUE TITLE
How to match aganist all columns ?

### ISSUE THREAD

**Issue by akissa** [AdrielVelazquez/sqlalchemy-sphinx#1]
Hi

Is it possible to match against all columns in the index i.e the `SphinxQL` query `SELECT id FROM test1 WHERE MATCH('is this a good plan?');`

**Comment by akissa** [comment]
Using func.match generates an exception so i guess this is a bug.
`File "/usr/lib/python2.6/site-packages/sqlalchemy_sphinx/dialect.py", line 168, in check_match_clause
    func_left, func_right = clause.clauses
ValueError: need more than 1 value to unpack`

**Comment by AdrielVelazquez** [comment]
@akissa I can modify the following. 
https://github.com/AdrielVelazquez/sqlalchemy-sphinx/blob/master/sqlalchemy_sphinx/dialect.py#L79

and include the generic func.match to take arbitrary values as long as it's valid SphinxQL. 

I can have another release this weekend with that change.

**Comment by akissa** [comment]
@AdrielVelazquez It think you should remove the `visit_match_func` totally as using sqlalchemy's `func.match` works correctly for me. I do not know if there is another use case there since you are only matching `match` You may need to remove the function condition in `check_match_clause` as well.

Am currently testing with the two commented out and have not run into any issues but still early to tell what the impact is.

**Comment by akissa** [comment]
@AdrielVelazquez Here is my attempt at fixing the two issues, i do not know sqlalchemy internals that well so maybe there is a better way.
https://github.com/akissa/sqlalchemy-sphinx/commit/f8f0c4777df30494bd3a7fca8efad077a5a1d3c7
https://github.com/akissa/sqlalchemy-sphinx/commit/9c7f2eaeb3e218beb6c9be902789108664125eef

**Comment by AdrielVelazquez** [comment]
https://pypi.org/project/sqlalchemy-sphinx/0.9.0/

Merged the recent two PRs, hopefully those resolve these issues.
