### ISSUE TITLE
Parameters not correctly escaped.

### ISSUE THREAD

**Issue by akissa** [AdrielVelazquez/sqlalchemy-sphinx#2]
Parameters passed to match are not escaped correctly.

Example query
`sphinx_session.query(MockSphinxModel).filter(MockSphinxModel.country.match("logwa'tch")).limit(1)`

Exception raised
`sqlalchemy.exc.ProgrammingError: (_mysql_exceptions.ProgrammingError) (1064, "sphinxql: syntax error, unexpected IDENT, expecting ')' near 'tch)')`

**Comment by AdrielVelazquez** [comment]
I'll fix this bug as well to make sure all strings are escaped.

**Comment by akissa** [comment]
@AdrielVelazquez Thanks

**Comment by AdrielVelazquez** [comment]
https://pypi.org/project/sqlalchemy-sphinx/0.9.0/

Merged the recent two PRs, hopefully those resolve these issues.
